{
    'name': "Servicios Tecnologicos",
    'summary': "Servicios Tecnologicos",
    'description': """
         Servicios Tecnologicos
     """,
    'author': "AK Digital Soluciones",
    'website': "https://www.ak.com.ni",
    "category": "Accounting",
    'version': '15.0',
    'depends': ['crm_helpdesk','base', 'hr', 'product', 'product_brand', 'helpdesk','project','helpdesk_timesheet','mail','crm'],
    'data': ['security/ir.model.access.csv',
             'views/menu.xml',
             'data/template_email_comercial_akd.xml',
             "data/secuencia.xml",
             'views/inherit_kanban_crm.xml',
             'views/form_bitacora.xml',
             'views/form_plantilla.xml',
             'views/lineas_bitacora.xml',
             'views/equipo_entrust.xml',
             'views/ticket_lead.xml',
             'views/vista_ticket.xml',
             'views/crm_lead_ticket.xml',
             'views/contrato_entrust.xml',
             "views/product_template.xml",
             'views/entrega_producto.xml',
             "views/boton_contratos_venta.xml",
             "views/botones_ticket.xml",
             "views/boton_fichas.xml",
             "views/mantenimientos.xml",
             "views/reporte_inspeccion.xml",
             "views/correo_encargado.xml",
             "views/correo_responsable.xml",
             "views/correo_mantenimiento_quince.xml",
             "views/correo_mantenimiento_treinta.xml",
             "views/correo_mantenimiento_quince_cliente.xml",
             "report/bitacora_servicio.xml",
             "report/reporte_ficha.xml",
             "report/reporte_inspeccion.xml",
             "report/contrato_mantenimiento_entrust_esc.xml"],


}
